version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8081:80"
        volumes:
            - .:/app
        links:
            - php
        depends_on:
            - db

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/

    db:
        build:
            context: .
            dockerfile: docker/postgre/Dockerfile
        ports:
            - "6432:5432"
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: silnehaslo
            POSTGRES_DB: ifilmdb