version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8081:80"
        volumes:
            - .:/app
        links:
            - php
        depends_on:
            - db
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/

    db:
        image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ifilm
        ports:
          - "7432:5432"
        volumes:
          - ./_data/postgres:/var/lib/postgres